fragment PropertySummary on Property {
  slug
  transactionType
  address
  district
  meters
  features(first: 3) {
    ...Feature
  }
  cost
  costCurrency
  expenses
  photos(first: 5) {
    url
  }
}
